# Generated by Django 4.2.1 on 2023-06-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0010_reply_section_topic_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
