# Generated by Django 4.2.1 on 2023-06-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0011_alter_reply_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='name',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
