# Generated by Django 4.2.1 on 2023-06-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0015_reply_user_section_user_topic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='section',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
    ]
