# Generated by Django 4.2.1 on 2023-06-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0017_reply_user_section_user_topic_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='user',
            new_name='owner',
        ),
    ]
